#!/bin/bash

SAVED_PWD=$PWD

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd "$DIR"

if [ "$#" -ne 1 ]; then
    echo "Pass one argument: the keypair nickname (example: server2)"
    exit 1
fi

if [[ -f "$1" || -f "$1.pub" || -f "$1.pem" ]]; then
    echo "Please delete any existing files in this directory starting with '$1'."
    exit 1
fi

mkdir -p "keys/$1"

ssh-keygen -f "$1" -P ""
# ssh-keygen -f "$1.pub" -e -m pem > "$1.pem"
ssh-keygen -f "$1.pub" -e -m PKCS8 > "$1.pem"
rm "$1.pub"
mv "$1.pem" "keys/public/$1.pub"
mv "$1" "keys/$1/$1.priv"
